config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    root 'page#home'
    get '/home' => 'page#home', :as => 'home'
    get '/account' => 'page#account', :as => 'account'
    get '/update_pref' => 'user#update_preferences', :as => 'update_pref'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
    email.match(/[^@]+/).to_s
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :language_set

  def language_set
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/page_controller.rb
# frozen_string_literal: true

class PageController < ApplicationController
  before_action :authenticate_user!, only: [:account]

  def home
    @news = NewsApiHelper.call(country: I18n.locale, category: user_pref).res
  end

  def account; end

  private

  def user_pref
    if current_user && !current_user.preference.nil?
      current_user.preference
    else
      'general'
    end
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  def update_preferences
    User.find_by(email: current_user.email).update(preference: params[:pref])
    respond_to { |format| format.js }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def user_preferences
    [
      [t('account_page.news_type.business'), 'business'],
      [t('account_page.news_type.health'), 'health'],
      [t('account_page.news_type.entertainment'), 'entertainment'],
      [t('account_page.news_type.general'), 'general'],
      [t('account_page.news_type.science'), 'science'],
      [t('account_page.news_type.sports'), 'sports'],
      [t('account_page.news_type.technology'), 'technology']
    ]
  end
end

app/helpers/page_helper.rb
# frozen_string_literal: true

module PageHelper
  def usd_rate
    ExchangeRate.call(val: 1, from: 'USD', to: 'RUB').res * 100
  end

  def eur_rate
    ExchangeRate.call(val: 1, from: 'EUR', to: 'RUB').res * 100
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/layouts/_devise_notifications.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Новости</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar news-header" role="navigation" aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <div class="logo">
              <div class="after-name">DailyNews</div>
            </div>
          </a>
          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <div class="navbar-item">
              <div class="buttons">
                <%= link_to t('main_page.home_link'), home_path, class: "button is-link is-rounded" %>
                <%= link_to t('main_page.setting'), account_path, class: "button is-link is-rounded" %>
              </div>
            </div>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <button class="button is-rounded is-small"><%= link_to 'EN', locale: :us %></button>
                <button class="button is-rounded is-small"><%= link_to 'RU', locale: :ru %></button>
              </div>
            </div>
            <div class="navbar-item">
              <div class="buttons">
                <% if current_user %>
                  <%= link_to t('main_page.signout'), destroy_user_session_url, method: :delete, class: "button is-danger is-rounded" %>
                <% else %>
                  <%= link_to t('main_page.signup'), new_user_registration_path, class: "button is-info is-rounded" %>
                  <%= link_to t('main_page.signin'), new_user_session_path, class: "button is-success is-rounded" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/page/account.html.erb
<div class="container news-content">
  <div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-3"><%= current_user.username %></p>
        <p class="subtitle is-6"><%= current_user.email %></p>
        <p class="subtitle is-6"><%= t 'account_page.since' %><%= current_user.created_at %></p>
      </div>
    </div>

    <div class="content">
      <div class="title"><%= t 'account_page.preffered_news' %></div> 

      <%= form_tag url_for(:action => 'update_preferences', :controller => 'user'), :method => 'get', remote: true do %>
      <div class="select">
        <%= select_tag :pref, options_for_select(user_preferences) %>
      </div>
      <div class="content news-content">
        <%= submit_tag t('account_page.submit'), class: "button is-primary" %>  
      </div>  
      <% end %>
    </div>
    <p class="help is-success res-info"></p>
  </div>
</div>  
</div>

app/views/page/home.html.erb
<div class="container news-content">
  <div class="columns">
    <div class="column">
      <%= render 'layouts/devise_notifications.html.erb' %>
      <% @news.each do |news| %>
        <%= link_to news.url do %>
          <div class="card news-card">
            <div class="card-content">
              <p class="title">
                <%= news.title %>
              </p>
              <p class="subtitle">
                <%= news.description %>
              </p>
            </div>
            <footer class="card-footer">
              <p class="card-footer-item">
                <span>
                  <%= link_to t('main_page.source'), news.url %>
                </span>
              </p>
            </footer>
          </div>
        <% end %>
      <% end %>      
    </div>
    <div class="column is-one-third">
      <div class="box exchange-rate-box">
        <div class="content">
          <div class="exchange-rate-value"><%= t 'main_page.exch' %></div>
          <div class="exchange-rate-value">$ <%= usd_rate %></div>
          <div class="exchange-rate-value">€ <%= eur_rate %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/update_preferences.js.erb
var appendText = `
  <%= t 'account_page.result_sub' %>
`

$('.res-info').append(appendText)